# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspectrum', '0006_auto_20170527_1039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='states',
            unique_together=set([('url', 'owner', 'name')]),
        ),
    ]
