# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectrum', '0007_auto_20170609_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='css_code',
            field=models.TextField(default=''),
        ),
    ]
