# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettingstarted', '0004_auto_20170523_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='css_code',
            field=models.TextField(default=None),
        ),
    ]
